project:
  type: website
  output-dir: docs # required, as github pages will read from docs folder

website:
  title: "Sustainable Inland Fisheries" # left of coloured top naviation bar
  favicon: images/sif.png  #ASTA: it would be good to have this image on the top bar, in the left corner, but not sure how to add it
  page-navigation: true
  navbar: 
    background: "white" # colour of the top navigation bar (can use hex)
  sidebar:
    style: "docked"
    search: false  #ASTA: tried to remove the search bar option, as it is not really doing anything, but it's still there
    contents:
#      - href: index.qmd
#        text: "Home" 
        - href: models.qmd
          text: "Overview of models" 
        - section: "CPUE standardisation"
          #href: CPUEstandard.qmd
          contents:
            - text: "1. GLM based standardisation" 
              href: GLM_standardisation.qmd 
            - text: "2. Zero inflated model for catch" 
              href: Zero_inflated_model.qmd 
            - text: "3. Bayesian model" 
              href: Bayesian_inla.qmd 
        - section: "Surplus production (SP) models"
          #href: SP_introduction.qmd
          contents:
            - text: "4. Understand SP models" 
              href: surplus-production.qmd 
            - text: "5. SP models with JABBA" 
              href: jabba_models.qmd 
        - section: "Fish growth models"
          #href: fish_growth.qmd
          contents:
            - text: "6. Von-Bertallanfy growth" 
              href: von-bertalanffy.qmd 
            - text: "7. Temperatue impacts on growth" 
              href: temperature_growth.qmd 
            - text: "8. Detecting growth changes" 
              href: growth_change.qmd 
            - text: "9. Detecting size changes" 
              href: detecting_size.qmd 
        - section: "Machine learning (ML) models"
          #href: machine_learning.qmd
          contents:
            - text: "10. ML for species identification" 
              href: ML_fish_species.qmd 
            - text: "11. ML for fish size estimation" 
              href: ML_fish_size.qmd 
        - section: "Satellite data analysis"
          #href: satelite_data.qmd
          contents:
            - text: "12. Getting temperature data" 
              href: satelite_temp.qmd 
            - text: "13. Getting chlA data" 
              href: satelite_chla.qmd 
        - section: "Size based ecosystem models"
          #href: curonian_model.qmd 
          contents:
            - text: "14. Curonian lagoon model" 
              href: curonian_mizer.qmd 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

