project:
  type: website
  output-dir: ./docs/lt # required, as github pages will read from docs folder

language: custom.yml

website:
  title: "Lydekai paliepus: tvari vidaus vandenų žvejyba" # left of coloured top naviation bar
  page-navigation: true
  search: false # you can toggle this to true/false for the search bar (personally i dont mind it to search within the website/pages) - Freddie
  navbar: 
    logo: images/sif_sm.png  # logo displayed at the top left of the webpage
    background: "white" # colour of the top navigation bar (can use hex)
    right:
      - href: https://fishsizeproject.github.io/models/lt/index.html
        text: Lietuvių
      - href: https://fishsizeproject.github.io/models/index.html
        text: English
  sidebar:
    style: "floating"
    contents:
#      - href: index.qmd
#        text: "Home" 
        - href: models.qmd
          text: "Modelių apžvalga" 
        - section: "Sugavimų standartizacijos modeliai"
          #href: CPUEstandard.qmd
          contents:
            - text: "1. Linijiniais modeliais paremta sugavimų standartizacija" 
              href: GLM_standardisation.qmd 
            - text: "2. Sugavimų modeliai su daug nulinių stebėjimų" 
              href: Zero_inflated_model.qmd 
            - text: "3. Bajeso metodu paremtas standartizacijos modelis" 
              href: Bayesian_inla.qmd 
        - section: "Pridėtinės produkcijos modeliai"
          #href: SP_introduction.qmd
          contents:
            - text: "4. Kaip veikia pridėtinės produkcijos modeliai" 
              href: surplus-production.qmd 
            - text: "5. Pridėtinės produkcijos modeliai su JABBA" 
              href: jabba_models.qmd 
        - section: "Žuvų augimo modeliai"
          #href: fish_growth.qmd
          contents:
            - text: "6. Von-Bertallanfy augimo modelis" 
              href: von-bertalanffy.qmd 
            - text: "7. Temperatūros įtaka žuvų augimui" 
              href: temperature_growth.qmd 
            - text: "8. Modelis augimo greičio pakitimams įvertinti" 
              href: growth_change.qmd 
        #    - text: "9. Detecting size changes" 
        #      href: detecting_size.qmd 
        - section: "Dirbtinio intelekto (DI) modeliai"
          #href: machine_learning.qmd
          contents:
            - text: "9. DI modelis žuvų rūšių nustatymui" 
              href: ML_fish_species.qmd 
            - text: "10. DI modelis žuvų dydžio nustatymui" 
              href: ML_fish_size.qmd 
        - section: "Palydovinių duomenų analizė"
          #href: satelite_data.qmd
          contents:
            - text: "11. Palydoviniai temperatūros duomenys" 
              href: satelite_temp.qmd 
            - text: "12. Palydoviniai chlorofilo A duomenys" 
              href: satelite_chla.qmd 
        - section: "Dydžiu paremti ekosistemų modeliai"
          #href: curonian_model.qmd 
          contents:
            - text: "13. Kuršių marių ekosistemos modelis" 
              href: curonian_mizer.qmd 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


