project:
  type: website
  output-dir: docs # required, as github pages will read from docs folder

website:
  title: "Sustainable Inland Fisheries" # left of coloured top naviation bar
  page-navigation: true
  navbar: 
    background: "pink" # colour of the top navigation bar (can use hex)
  sidebar:
    style: "docked"
    search: true
    contents:
#      - href: index.qmd
#        text: "Home" # how the page appears in the left navigation bar#
        - href: models.qmd
          text: "Models home" # how the page appears in the left navigation bar
       - section: "CPUE standardisation"
         contents:
            - href: GLM_standardisation.qmd 
              text: "GLM based standardisation" # how it appears in the left navigation 
            - href: Zero_inflated_model.qmd 
              text: "Zero inflated model for catch" # how it appears in the left navigation 
            - href: Bayesian_inla.qmd 
              text: "Bayesian model" # how it appears in the left navigation 
            
            
            
            
          - href: models.qmd 
            text: "Overview of models" # how it appears in the left navigation 
          - href: surplus-production.qmd 
            text: "Surplus production"
          - href: temperature.qmd 
            text: "Temperature models"
          - href: von-bertalanffy.qmd 
            text: "Von Bertalanffy growth"
          - href: mqmf.qmd 
            text: "MQMF models"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

