project:
  type: website
  output-dir: ./docs # required, as github pages will read from docs folder

lang: en

website:
  title: "Sustainable Inland Fisheries" # left of coloured top naviation bar
  page-navigation: true
  search: false # you can toggle this to true/false for the search bar (personally i dont mind it to search within the website/pages) - Freddie
  navbar: 
    logo: images/sif_sm.png  # logo displayed at the top left of the webpage
    background: "white" # colour of the top navigation bar (can use hex)
    right:
      - href: https://fishsizeproject.github.io/models/lt/models.html
        text: Lietuvių
      - href: https://fishsizeproject.github.io/models/en/models.html
        text: English
  sidebar:
    style: "docked"
    contents:
#      - href: index.html
#        text: "Home" 
        - href: ./en/models.html
          text: "Overview of models" 
        - section: "CPUE standardisation"
          #href: CPUEstandard.html
          contents:
            - text: "1. GLM based standardisation" 
              href: ./en/GLM_standardisation.html 
            - text: "2. Zero inflated model for catch" 
              href: ./en/Zero_inflated_model.html 
            - text: "3. Bayesian model" 
              href: ./en/Bayesian_inla.html 
        - section: "Surplus production (SP) models"
          #href: SP_introduction.html
          contents:
            - text: "4. Understand SP models" 
              href: ./en/surplus-production.html 
            - text: "5. SP models with JABBA" 
              href: ./en/jabba_models.html 
        - section: "Fish growth models"
          #href: fish_growth.html
          contents:
            - text: "6. Von-Bertallanfy growth" 
              href: ./en/von-bertalanffy.html 
            - text: "7. Temperature impacts on growth" 
              href: ./en/temperature_growth.html 
            - text: "8. Detecting growth changes" 
              href: ./en/growth_change.html 
            - text: "9. Detecting size changes" 
              href: ./en/detecting_size.html 
        - section: "Machine learning (ML) models"
          #href: machine_learning.html
          contents:
            - text: "10. ML for species identification" 
              href: ./en/ML_fish_species.html 
            - text: "11. ML for fish size estimation" 
              href: ./en/ML_fish_size.html 
        - section: "Satellite data analysis"
          #href: satelite_data.html
          contents:
            - text: "12. Getting temperature data" 
              href: ./en/satelite_temp.html 
            - text: "13. Getting chlA data" 
              href: ./en/satelite_chla.html 
        - section: "Size based ecosystem models"
          #href: curonian_model.html 
          contents:
            - text: "14. Curonian lagoon model" 
              href: ./en/curonian_mizer.html 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

